version: '3.8'

services:
  mysql:
    image: wtpotu/grocerygo-mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"      # Set via .env
      MYSQL_DATABASE: "${MYSQL_DATABASE}"          # Set via .env
    ports:
      - "3307:3306"
    networks:
      - ofs-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: wtpotu/grocerygo-backend:latest
    container_name: backend_container
    environment:
      MYSQL_HOST: "mysql"                           # Service name for networking
      MYSQL_USER: "${MYSQL_USER}"                   # Set via .env
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"           # Set via .env
      MYSQL_DATABASE: "${MYSQL_DATABASE}"           # Set via .env
      SESSION_SECRET: "${SESSION_SECRET}"           # Set via .env
      PORT: "${PORT}"                               # Set via .env
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - ofs-network

  frontend:
    image: wtpotu/grocerygo-frontend:latest
    container_name: frontend_container
    ports:
      - "3000:80"
    networks:
      - ofs-network

networks:
  ofs-network:
    driver: bridge