version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./database/db.sql:/docker-entrypoint-initdb.d/init.sql  # Load the SQL file at startup
    ports:
      - "3306:3306"
    networks:
      - ofs-network

  backend:
    build: ./server  # Path to the backend Dockerfile
    container_name: backend_container
    env_file:
      - .env  # Load the .env file for sensitive variables
    volumes:
      - ./server:/app/OFS/server  # Sync backend code for live changes
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - ofs-network

  frontend:
    build: ./client  # Path to the frontend Dockerfile
    container_name: frontend_container
    ports:
      - "3000:80"
    networks:
      - ofs-network

networks:
  ofs-network:
    driver: bridge