services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./database/db.sql:/docker-entrypoint-initdb.d/init.sql  # Load the SQL file at startup
    ports:
      - "3307:3306"
    networks:
      - ofs-network

  backend:
    build: ./server  # Path to the backend Dockerfile
    container_name: backend_container
    env_file:
      - ./server/.env  # Path to the .env file inside the server folder
    volumes:
      - ./server:/app/OFS/server  # Sync backend code for live changes
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - ofs-network

  frontend:
    build: ./client  # Path to the frontend Dockerfile
    container_name: frontend_container
    ports:
      - "3000:80"
    networks:
      - ofs-network

networks:
  ofs-network:
    driver: bridge