name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Log in to Docker Hub using secrets for Docker Hub credentials
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker images with docker-compose
      - name: Build and push Docker images with docker-compose
        run: |
          docker-compose -f docker-compose.yml build  # Build all services defined in docker-compose.yml
          docker-compose -f docker-compose.yml push  # Push the images to Docker Hub
